### ISSUE TITLE
5.3.0 compat

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/minetest_docker#4]
## TODO
* [x] remove `game_tnt_crash.patch`
* [ ] ~~possibly remove `auth_iterater_perf.patch` (if it breaks with the new auth-db)~~

## Blockers
* [x] rebase/fix patch: `minetest_async_pg.patch`

## Nice to have
* [ ] add more metrics (to investigate possible mapsending bug)
* [ ] more threadpool magic like `minetest_async_mapsending.patch`
